services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: laravel-webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel-network
        depends_on:
            - app

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_admin_template
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: laravel
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local